// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuR8tbsgUabwG92kqg_1_lu95w9_u1kw',
    appId: '1:178112894436:web:f9c1647933b074147663f1',
    messagingSenderId: '178112894436',
    projectId: 'quiz-app-77d37',
    authDomain: 'quiz-app-77d37.firebaseapp.com',
    storageBucket: 'quiz-app-77d37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6NrkK7rPx49HecC7X3DP8OmK_SLbpqw',
    appId: '1:178112894436:android:f114b2dd3ef437407663f1',
    messagingSenderId: '178112894436',
    projectId: 'quiz-app-77d37',
    storageBucket: 'quiz-app-77d37.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuuR8tbsgUabwG92kqg_1_lu95w9_u1kw',
    appId: '1:178112894436:web:696947cac4374a137663f1',
    messagingSenderId: '178112894436',
    projectId: 'quiz-app-77d37',
    authDomain: 'quiz-app-77d37.firebaseapp.com',
    storageBucket: 'quiz-app-77d37.appspot.com',
  );
}
