// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCL1QRnJ4Gby9-z9otayDygDnkQogPBY',
    appId: '1:626137820503:web:a5fcf01483359876bc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    authDomain: 'quizapp-3b15c.firebaseapp.com',
    storageBucket: 'quizapp-3b15c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XL8n5VVEaViHNmVvLVswS6ZH2vIAGO0',
    appId: '1:626137820503:android:c9ae7fd3a8c56b2ebc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    storageBucket: 'quizapp-3b15c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMCL1QRnJ4Gby9-z9otayDygDnkQogPBY',
    appId: '1:626137820503:web:e125245a70eb4a07bc2212',
    messagingSenderId: '626137820503',
    projectId: 'quizapp-3b15c',
    authDomain: 'quizapp-3b15c.firebaseapp.com',
    storageBucket: 'quizapp-3b15c.appspot.com',
  );

}